name: ❓ 질문 / 도움 요청
description: 궁금한 점이나 도움이 필요하신가요?
title: "[QUESTION] "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ❓ 질문 / 도움 요청
        궁금한 점이 있으시다면 편하게 물어보세요! 팀원들이 도와드리겠습니다.

  - type: dropdown
    id: category
    attributes:
      label: 질문 카테고리
      description: 어떤 분야에 대한 질문인가요?
      options:
        - 🚀 설치 및 실행
        - 🔧 개발 환경 설정
        - 💻 코드 작성 방법
        - 🏗️ 아키텍처 및 설계
        - 🐛 디버깅 및 문제 해결
        - 🔐 인증 및 보안
        - 🗄️ 데이터베이스
        - 🌐 API 사용법
        - 📦 배포 및 운영
        - 🎨 UI/UX 구현
        - 📱 프론트엔드 (React)
        - ☕ 백엔드 (Spring Boot)
        - 🐳 Docker / 인프라
        - 📖 문서 이해
        - 🤝 협업 및 워크플로우
        - 기타
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: 질문 내용
      description: 무엇이 궁금하신가요? 구체적으로 작성해주세요.
      placeholder: |
        예시:
        - Spring Cloud Gateway에서 JWT 토큰을 검증하는 방법이 궁금합니다.
        - Hocuspocus를 사용해서 실시간 동기화를 구현하려는데 어디서부터 시작해야 할까요?
        - 약-음식 충돌 룰을 추가하려면 어떤 파일을 수정해야 하나요?
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: 시도한 방법
      description: 이미 시도해본 것들이 있나요?
      placeholder: |
        예시:
        - ARCHITECTURE.md 문서를 읽어봤지만 JWT 검증 부분은 자세히 나와있지 않았습니다
        - Hocuspocus 공식 문서를 봤는데 React와 통합하는 예제가 없었습니다
        - Google에서 "Spring Cloud Gateway JWT validation"을 검색했습니다

  - type: textarea
    id: context
    attributes:
      label: 추가 정보
      description: 상황을 이해하는데 도움이 될 만한 정보를 작성해주세요
      placeholder: |
        예시:
        - 작업 중인 브랜치: feature/family-network
        - 참고하고 있는 파일: src/services/AuthService.java
        - 관련 에러 메시지나 로그

  - type: textarea
    id: code
    attributes:
      label: 관련 코드 (선택사항)
      description: 질문과 관련된 코드가 있다면 첨부해주세요
      placeholder: |
        ```java
        public class GatewayConfig {
            // 여기에 JWT 검증 로직을 추가하고 싶습니다
        }
        ```
      render: markdown

  - type: dropdown
    id: urgency
    attributes:
      label: 긴급도
      description: 얼마나 빨리 답변이 필요한가요?
      options:
        - 🔴 Urgent - 작업이 막혀있음
        - 🟡 Normal - 며칠 내 답변 희망
        - 🟢 Low - 여유 있게 기다릴 수 있음
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      description: 질문하기 전에 확인해주세요!
      options:
        - label: 프로젝트 문서를 먼저 확인했습니다
          required: true
        - label: 이미 올라온 질문인지 검색해봤습니다
          required: true
        - label: 충분히 구체적으로 질문을 작성했습니다
          required: false
